{
  config,
  inputs,
  lib,
  ...
}:
let
  secretsModule = sysArgs: {
    # This option simply wraps `age.secrets` setting `file` to the value generated by flake's `secrets` module
    options.secrets = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule (
          { name, ... }:
          {
            freeformType = lib.types.attrs;
            options = { };
            config = {
              file = config.secrets.${name}.file;
            };
          }
        )
      );
      default = { };
    };

    config.age.secrets = sysArgs.config.secrets;
  };

  hostKeysFor =
    systems:
    systems
    |> lib.attrValues
    |> lib.map (
      sys:
      sys.config.age.secrets
      |> lib.mapAttrs (
        _: secret: {
          publicKeys = [ config.secrets."ssh_host_key_${sys.config.networking.hostName}".sshPublicKey ];
        }
      )
    )
    |> lib.mkMerge;
in
{
  config.flake.modules.nixos.base = nArgs: {
    imports = [
      inputs.agenix.nixosModules.age
      (secretsModule nArgs)
    ];
  };

  config.flake.modules.darwin.base = dArgs: {
    imports = [
      inputs.agenix.darwinModules.default
      (secretsModule dArgs)
    ];
  };

  config.secrets = lib.mkMerge [
    (hostKeysFor config.flake.nixosConfigurations)
    (hostKeysFor config.flake.darwinConfigurations)
  ];
}
