name: deploy
on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Host'
        required: true
        type: string

jobs:
  lockfile:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          token: ${{secrets.SEVENOFNINE_TOKEN}}
      - name: Deploy
        run: |
          nixos-rebuild switch \
            --flake ".#${{ inputs.host }}" \
            --target-host "root@${{ inputs.host }}.wg.aciceri.dev" \
            --sudo --print-build-logs
