# Autogenerated
{ pkgs ? import <nixpkgs> { } }: {
  asciinema-player = pkgs.callPackage ./asciinema-player/_package.nix { };
  claude-code = pkgs.callPackage ./claude-code/_package.nix { };
  hyphenopoly = pkgs.callPackage ./hyphenopoly/_package.nix { };
  mirror-checks = pkgs.callPackage ./mirror-checks/_package.nix { };
  yt-dlp-master = pkgs.callPackage ./yt-dlp-master/_package.nix { };
}