# Autogenerated
{ pkgs ? import <nixpkgs> { } }: {
  asciinema-player = pkgs.callPackage ./asciinema-player/_package.nix { };
  hyphenopoly = pkgs.callPackage ./hyphenopoly/_package.nix { };
  mirror-checks = pkgs.callPackage ./mirror-checks/_package.nix { };
  yt-dlp-latest = pkgs.callPackage ./yt-dlp-latest/_package.nix { };
}